[supervisord]
user = root
nodaemon = true
logfile = /dev/null
logfile_maxbytes = 0

[program:php-fpm]
command = php-fpm -F
stdout_logfile = /proc/self/fd/1
stdout_logfile_maxbytes = 0
stderr_logfile = /proc/self/fd/2
stderr_logfile_maxbytes = 0

[program:nginx]
command = nginx -g 'daemon off;'
stdout_logfile = /proc/self/fd/1
stdout_logfile_maxbytes = 0
stderr_logfile = /proc/self/fd/2
stderr_logfile_maxbytes = 0

[program:cron]
command = cron -f
stdout_logfile = /proc/self/fd/1
stdout_logfile_maxbytes = 0
stderr_logfile = /proc/self/fd/2
stderr_logfile_maxbytes = 0

[program:queue-worker]
command = php /var/www/artisan queue:work --tries=3
stdout_logfile = /proc/self/fd/1
stdout_logfile_maxbytes = 0
stderr_logfile = /proc/self/fd/2
stderr_logfile_maxbytes = 0
